// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTwoTabletblStudentsAndtblClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTwoTabletblStudentsAndtblClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "202208190647179_addTwoTable tblStudentsAnd tblClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
